# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171230_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post1',
        ),
    ]
